title: Services
fields:
  -
    handle: services
    field:
      mode: default
      type: entries
      localizable: false
      listable: hidden
      display: Services
      instructions: 'Select the services you want to link to.'
      validate: required
      collections:
        - services
